version: "3.7"

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.252
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SERVERURL=${WIREGUARD_SERVER_URL}
      - SERVERPORT=${WIREGUARD_SERVER_PORT}
      - PEERS=${WIREGUARD_PEERS}
      - PEERDNS=192.168.90.253 # Pihole DNS
    volumes:
      - $USERDIR/docker/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      # This port should be port forwarded
      - ${WIREGUARD_SERVER_PORT}:${WIREGUARD_SERVER_PORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    depends_on:
      - pihole

  ## Pihole - Ad-blocker
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.253
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    ports:
    # Open this ports for LAN ONLY
      - "53:53/tcp"
      - "53:53/udp"
      - "1180:80/tcp"
      - "1443:443/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - $USERDIR/docker/pihole/pihole:/etc/pihole
      - $USERDIR/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
      ## Run `touch ~/docker/pihole/pihole.log` before starting pihole
      - $USERDIR/docker/pihole/pihole.log:/var/log/pihole.log
    environment:
      - TZ=$TZ
      - VIRTUAL_HOST=pihole.${DOMAINNAME}
      - IPv6=False
      - WEBPASSWORD=$PIHOLE_PASSWORD
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.pihole-rtr.entrypoints=https"
      - "traefik.http.routers.pihole-rtr.rule=HostHeader(`pihole.$DOMAINNAME`)"
      - "traefik.http.routers.pihole-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.pihole-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.pihole-rtr.service=pihole-svc"
      - "traefik.http.services.pihole-svc.loadbalancer.server.port=80"
