version: "3.7"

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.252
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SERVERURL=${WIREGUARD_SERVER_URL}
      - SERVERPORT=${WIREGUARD_SERVER_PORT}
      - PEERS=${WIREGUARD_PEERS}
      - PEERDNS=192.168.1.89 # Pihole DNS
    volumes:
      - $USERDIR/docker/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      # This port should be port forwarded
      - ${WIREGUARD_SERVER_PORT}:${WIREGUARD_SERVER_PORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
