version: "3.7"

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.98
    deploy:
      resources:
        limits:
          cpus: "0.7"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022 #optional
    volumes:
      # Config
      - ${USERDIR}/docker/bazarr:/config
      # Disks
      - /mnt/:/disks/other/
      - ${USERDIR}/Downloads:/disks/hdd-sata-0/Downloads
      - ${USERDIR}/Media:/disks/hdd-sata-0/Media
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.bazarr-rtr.entrypoints=https"
      - "traefik.http.routers.bazarr-rtr.rule=HostHeader(`bazarr.$DOMAINNAME`)"
      - "traefik.http.routers.bazarr-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.bazarr-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.bazarr-rtr.service=bazarr-svc"
      - "traefik.http.services.bazarr-svc.loadbalancer.server.port=6767"
